version: '3.7'

services:
  mc2.crudtest.customerservice.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "5000:80"
      - "7000:443"
  mssql:
    container_name: mssql
    environment:
      SA_PASSWORD: "Aa123456"
      ACCEPT_EULA: "Y"
    restart: always
    ports:
      - "1483:1433"

  eventstore:
    container_name: eventstore
    ports:
      - '2113:2113'
      - '1113:1113'
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=all
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_ADMIN_USER=admin
      - EVENTSTORE_ADMIN_PASS=changeit